### ISSUE TITLE
Switch ALAxisVertical and ALAxisHorizontal

### ISSUE THREAD

**Issue by jonaszmclaren** [PureLayout/PureLayout#125] opened 2016-02-22 15:32 UTC
Hello,

in PureLayoutDefines.h at lines 129-132 there is:
```
/** A vertical line equidistant from the view's left and right edges. */
    ALAxisVertical = NSLayoutAttributeCenterX,
    /** A horizontal line equidistant from the view's top and bottom edges. */
    ALAxisHorizontal = NSLayoutAttributeCenterY,
```

Shouldn't the vertical axis be Y, and horizontal X?

Best regards,
Jonasz

**Comment by smileyborg** [comment] 2016-02-22 15:40
Duplicate of #33

**Closed by smileyborg** 2016-02-22 15:40 UTC
Labels: duplicate
