### ISSUE TITLE
Semantic Issues

### ISSUE THREAD

**Issue by CharlieCamp98** [PureLayout/PureLayout#226] opened 2018-09-07 19:29 UTC
When building my application, I get semantic warnings similar to the following:

'NSLayoutYAxisAnchor' is only available on iOS 9.0 or newer
 'NSLayoutYAxisAnchor' is only available on iOS 9.0 or newer

Is it possible to get rid of these warning messages? There's 24 of them every time I compile my application. I set my build target to iOS 9.0 -- not sure why this is happening.

**Comment by lwdupont** [comment] 2018-09-07 22:04
Ah, I think I know what's going on.. Xcode 9 has a new way to check for availability (@available) - see https://medium.com/@derrickho_28266/xcode-9-ad8ee9c4cf9. 

For now can you turn off warnings in your Pod file? I'll add a task to fix it.

**Comment by toohotz** [comment] 2018-09-13 16:04
@lwdupont I have a PR incoming that should resolve this, was hanging tight for the GM of Xcode 10 to be released.

**Comment by lwdupont** [comment] 2018-09-13 17:27
@toohotz Super, thank you!

**Comment by ismyhc** [comment] 2018-10-21 13:15
@toohotz any update on this PR? Id love to clean up these warnings in my project :)

**Comment by lwdupont** [comment] 2018-10-21 15:34
I think I was waiting for the other person tagged in the pr, but thanks for the tickle, I'll get it merged this afternoon my time.

**Comment by ismyhc** [comment] 2018-10-21 21:07
Awesome!! 🙂

**Comment by ismyhc** [comment] 2018-10-26 12:38
@lwdupont any word on getting this merged and updating cocoapods version? :)

**Comment by lwdupont** [comment] 2018-10-26 16:16
@ismyhc Sorry, the week has gotten away from me. Let me try my work laptop right now. @toohotz couldn't reproduce my assert at the end of the unit testing, so hoping it's just my personal laptop.

**Comment by ismyhc** [comment] 2018-10-27 01:09
@lwdupont no worries! 🙂 I appreciate you working on it!

**Comment by lwdupont** [comment] 2018-10-27 18:07
Ok, released!

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  PureLayout (3.1.4) successfully published
 📅  October 27th, 11:04
 🌎  https://cocoapods.org/pods/PureLayout
 👍  Tell your friends!

**Closed by lwdupont** 2018-10-27 18:07 UTC

**Comment by ismyhc** [comment] 2018-10-29 12:57
@lwdupont awesome!! Thank you!
